# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5546a80f837277a2a1504ea0f4f7d016dc82b839d3bc06192356229d1dae67708e9bdae1b2d65ea5653b72c4ad7339df081a84bb81f819e95f4ef9ba56c52c1

test:
  secret_key_base: 17bb5fd3f9ac5def2baf11f243240bbfef65c8b59bb26e5ee539d7330a37fdd60286f4a35a5f3f82a4b69af9e646815fda498d02c093ac09c4074076fe837a7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
